/* ========= 元素データ（1-118）最小情報 ========= */
/* ========= 元素データ 1–118 ========= */
/* ========= 完全版 ELEMENTS 1–118 ========= */
export const ELEMENTS = [
  {num: 1,  sym:'H',  en:'Hydrogen',     ja:'水素',           fact:'宇宙で最も多い気体。'},
  {num: 2,  sym:'He', en:'Helium',       ja:'ヘリウム',       fact:'非常に軽く、風船に使用。'},
  {num: 3,  sym:'Li', en:'Lithium',      ja:'リチウム',       fact:'充電池の正極材料。'},
  {num: 4,  sym:'Be', en:'Beryllium',    ja:'ベリリウム',     fact:'X線管窓などに使われる軽金属。'},
  {num: 5,  sym:'B',  en:'Boron',        ja:'ホウ素',         fact:'耐熱ガラスやホウ酸に利用。'},
  {num: 6,  sym:'C',  en:'Carbon',       ja:'炭素',           fact:'ダイヤモンドやグラファイトの構成元素。'},
  {num: 7,  sym:'N',  en:'Nitrogen',     ja:'窒素',           fact:'空気の約78%を占める気体。'},
  {num: 8,  sym:'O',  en:'Oxygen',       ja:'酸素',           fact:'呼吸と燃焼に不可欠。'},
  {num: 9,  sym:'F',  en:'Fluorine',     ja:'フッ素',         fact:'最も電気陰性度が高い元素。'},
  {num:10,  sym:'Ne', en:'Neon',         ja:'ネオン',         fact:'ネオン管のオレンジ発光。'},
  {num:11,  sym:'Na', en:'Sodium',       ja:'ナトリウム',     fact:'食塩の主成分。'},
  {num:12,  sym:'Mg', en:'Magnesium',    ja:'マグネシウム',   fact:'軽量合金や発炎筒に利用。'},
  {num:13,  sym:'Al', en:'Aluminium',    ja:'アルミニウム',   fact:'軽く錆びにくい金属。'},
  {num:14,  sym:'Si', en:'Silicon',      ja:'ケイ素',         fact:'半導体チップの主材料。'},
  {num:15,  sym:'P',  en:'Phosphorus',   ja:'リン',           fact:'肥料・マッチ頭薬に使用。'},
  {num:16,  sym:'S',  en:'Sulfur',       ja:'硫黄',           fact:'火山にも多い黄色固体。'},
  {num:17,  sym:'Cl', en:'Chlorine',     ja:'塩素',           fact:'水道水の殺菌に利用。'},
  {num:18,  sym:'Ar', en:'Argon',        ja:'アルゴン',       fact:'溶接の不活性雰囲気ガス。'},
  {num:19,  sym:'K',  en:'Potassium',    ja:'カリウム',       fact:'細胞の浸透圧調整に重要。'},
  {num:20,  sym:'Ca', en:'Calcium',      ja:'カルシウム',     fact:'骨や貝殻の主成分。'},

  {num:21,  sym:'Sc', en:'Scandium',     ja:'スカンジウム',   fact:'高強度アルミ合金の添加元素。'},
  {num:22,  sym:'Ti', en:'Titanium',     ja:'チタン',         fact:'高耐食・高強度の軽金属。'},
  {num:23,  sym:'V',  en:'Vanadium',     ja:'バナジウム',     fact:'工具鋼を硬くする元素。'},
  {num:24,  sym:'Cr', en:'Chromium',     ja:'クロム',         fact:'ステンレス鋼の光沢を生む。'},
  {num:25,  sym:'Mn', en:'Manganese',    ja:'マンガン',       fact:'乾電池の材料。'},
  {num:26,  sym:'Fe', en:'Iron',         ja:'鉄',             fact:'建築や機械で最も使われる金属。'},
  {num:27,  sym:'Co', en:'Cobalt',       ja:'コバルト',       fact:'リチウムイオン電池や青色顔料。'},
  {num:28,  sym:'Ni', en:'Nickel',       ja:'ニッケル',       fact:'硬貨や耐食合金に利用。'},
  {num:29,  sym:'Cu', en:'Copper',       ja:'銅',             fact:'電線や配管に不可欠。'},
  {num:30,  sym:'Zn', en:'Zinc',         ja:'亜鉛',           fact:'めっきや乾電池に使用。'},
  {num:31,  sym:'Ga', en:'Gallium',      ja:'ガリウム',       fact:'青色LEDの半導体材料。'},
  {num:32,  sym:'Ge', en:'Germanium',    ja:'ゲルマニウム',   fact:'光ファイバ増幅材に利用。'},
  {num:33,  sym:'As', en:'Arsenic',      ja:'ヒ素',           fact:'GaAs半導体の構成元素。'},
  {num:34,  sym:'Se', en:'Selenium',     ja:'セレン',         fact:'光導電性を持つ非金属。'},
  {num:35,  sym:'Br', en:'Bromine',      ja:'臭素',           fact:'唯一の液体ハロゲン。'},
  {num:36,  sym:'Kr', en:'Krypton',      ja:'クリプトン',     fact:'高輝度ランプに使われる希ガス。'},

  {num:37,  sym:'Rb', en:'Rubidium',     ja:'ルビジウム',     fact:'原子時計の基準原子。'},
  {num:38,  sym:'Sr', en:'Strontium',    ja:'ストロンチウム', fact:'花火の赤色発色材。'},
  {num:39,  sym:'Y',  en:'Yttrium',      ja:'イットリウム',   fact:'赤色LEDや高温超伝導体。'},
  {num:40,  sym:'Zr', en:'Zirconium',    ja:'ジルコニウム',   fact:'原子炉の被覆管。'},
  {num:41,  sym:'Nb', en:'Niobium',      ja:'ニオブ',         fact:'超伝導合金に利用。'},
  {num:42,  sym:'Mo', en:'Molybdenum',   ja:'モリブデン',     fact:'耐熱鋼の添加元素。'},
  {num:43,  sym:'Tc', en:'Technetium',   ja:'テクネチウム',   fact:'人工元素、医療診断薬。'},
  {num:44,  sym:'Ru', en:'Ruthenium',    ja:'ルテニウム',     fact:'硬貨メッキや触媒。'},
  {num:45,  sym:'Rh', en:'Rhodium',      ja:'ロジウム',       fact:'自動車触媒の高価金属。'},
  {num:46,  sym:'Pd', en:'Palladium',    ja:'パラジウム',     fact:'水素吸蔵合金・宝飾品。'},
  {num:47,  sym:'Ag', en:'Silver',       ja:'銀',             fact:'導電率が最も高い金属。'},
  {num:48,  sym:'Cd', en:'Cadmium',      ja:'カドミウム',     fact:'ニカド電池・顔料。'},
  {num:49,  sym:'In', en:'Indium',       ja:'インジウム',     fact:'ITO透明導電膜に不可欠。'},
  {num:50,  sym:'Sn', en:'Tin',          ja:'スズ',           fact:'はんだやブリキに利用。'},
  {num:51,  sym:'Sb', en:'Antimony',     ja:'アンチモン',     fact:'難燃剤・鉛バッテリ合金。'},
  {num:52,  sym:'Te', en:'Tellurium',    ja:'テルル',         fact:'太陽電池 CdTe。'},
  {num:53,  sym:'I',  en:'Iodine',       ja:'ヨウ素',         fact:'殺菌や造影剤に使用。'},
  {num:54,  sym:'Xe', en:'Xenon',        ja:'キセノン',       fact:'キセノンヘッドライト。'},

  {num:55,  sym:'Cs', en:'Cesium',       ja:'セシウム',       fact:'最精密な原子時計に使用。'},
  {num:56,  sym:'Ba', en:'Barium',       ja:'バリウム',       fact:'消化器X線造影剤。'},
  {num:57,  sym:'La', en:'Lanthanum',    ja:'ランタン',       fact:'NiMH電池の負極合金。'},
  {num:58,  sym:'Ce', en:'Cerium',       ja:'セリウム',       fact:'研磨材・発火石に利用。'},
  {num:59,  sym:'Pr', en:'Praseodymium', ja:'プラセオジム',   fact:'ネオジム磁石を強化。'},
  {num:60,  sym:'Nd', en:'Neodymium',    ja:'ネオジム',       fact:'最強永久磁石 NdFeB。'},
  {num:61,  sym:'Pm', en:'Promethium',   ja:'プロメチウム',   fact:'β線電池に利用される人工元素。'},
  {num:62,  sym:'Sm', en:'Samarium',     ja:'サマリウム',     fact:'SmCo高耐熱磁石。'},
  {num:63,  sym:'Eu', en:'Europium',     ja:'ユウロピウム',   fact:'赤色蛍光体の発光中心。'},
  {num:64,  sym:'Gd', en:'Gadolinium',   ja:'ガドリニウム',   fact:'MRI造影剤に使用。'},
  {num:65,  sym:'Tb', en:'Terbium',      ja:'テルビウム',     fact:'高緑色輝度蛍光体。'},
  {num:66,  sym:'Dy', en:'Dysprosium',   ja:'ジスプロシウム', fact:'高温下で磁石の保磁力を向上。'},
  {num:67,  sym:'Ho', en:'Holmium',      ja:'ホルミウム',     fact:'最強の磁気モーメントを持つ。'},
  {num:68,  sym:'Er', en:'Erbium',       ja:'エルビウム',     fact:'光ファイバ増幅 EDF に使用。'},
  {num:69,  sym:'Tm', en:'Thulium',      ja:'ツリウム',       fact:'医療用ポータブルX線源。'},
  {num:70,  sym:'Yb', en:'Ytterbium',    ja:'イッテルビウム', fact:'Ybレーザーの添加イオン。'},
  {num:71,  sym:'Lu', en:'Lutetium',     ja:'ルテチウム',     fact:'PET診断薬の標識核種。'},

  {num:72,  sym:'Hf', en:'Hafnium',      ja:'ハフニウム',     fact:'原子炉制御棒や高kゲート材料。'},
  {num:73,  sym:'Ta', en:'Tantalum',     ja:'タンタル',       fact:'コンデンサや医療インプラント。'},
  {num:74,  sym:'W',  en:'Tungsten',     ja:'タングステン',   fact:'電球フィラメント・超硬工具。'},
  {num:75,  sym:'Re', en:'Rhenium',      ja:'レニウム',       fact:'ジェットエンジン超合金。'},
  {num:76,  sym:'Os', en:'Osmium',       ja:'オスミウム',     fact:'最も密度の高い金属。'},
  {num:77,  sym:'Ir', en:'Iridium',      ja:'イリジウム',     fact:'高温耐食性が最高クラス。'},
  {num:78,  sym:'Pt', en:'Platinum',     ja:'白金',           fact:'自動車触媒・宝飾品。'},
  {num:79,  sym:'Au', en:'Gold',         ja:'金',             fact:'貴金属・通貨の価値基準。'},
  {num:80,  sym:'Hg', en:'Mercury',      ja:'水銀',           fact:'常温で液体の金属。'},
  {num:81,  sym:'Tl', en:'Thallium',     ja:'タリウム',       fact:'光電池や特殊ガラス。'},
  {num:82,  sym:'Pb', en:'Lead',         ja:'鉛',             fact:'はんだ・バッテリー極板。'},
  {num:83,  sym:'Bi', en:'Bismuth',      ja:'ビスマス',       fact:'低融点合金や医薬品に安全使用。'},
  {num:84,  sym:'Po', en:'Polonium',     ja:'ポロニウム',     fact:'α線静電除去装置。'},
  {num:85,  sym:'At', en:'Astatine',     ja:'アスタチン',     fact:'放射線治療用α線源。'},
  {num:86,  sym:'Rn', en:'Radon',        ja:'ラドン',         fact:'放射性希ガスで健康影響に注意。'},

  {num:87,  sym:'Fr', en:'Francium',     ja:'フランシウム',   fact:'天然に極微量の超放射性元素。'},
  {num:88,  sym:'Ra', en:'Radium',       ja:'ラジウム',       fact:'かつて夜光塗料に使用。'},
  {num:89,  sym:'Ac', en:'Actinium',     ja:'アクチニウム',   fact:'放射線治療薬への応用研究。'},
  {num:90,  sym:'Th', en:'Thorium',      ja:'トリウム',       fact:'次世代溶融塩炉の核燃料候補。'},
  {num:91,  sym:'Pa', en:'Protactinium', ja:'プロトアクチニウム',fact:'希少で高放射性の金属。'},
  {num:92,  sym:'U',  en:'Uranium',      ja:'ウラン',         fact:'原子力発電・核兵器の燃料。'},
  {num:93,  sym:'Np', en:'Neptunium',    ja:'ネプツニウム',   fact:'高速炉燃料・核電池研究。'},
  {num:94,  sym:'Pu', en:'Plutonium',    ja:'プルトニウム',   fact:'核兵器・高速炉燃料。'},
  {num:95,  sym:'Am', en:'Americium',    ja:'アメリシウム',   fact:'家庭用煙感知器のα線源。'},
  {num:96,  sym:'Cm', en:'Curium',       ja:'キュリウム',     fact:'宇宙探査機RTG熱源。'},
  {num:97,  sym:'Bk', en:'Berkelium',    ja:'バークリウム',   fact:'超重元素合成ターゲット。'},
  {num:98,  sym:'Cf', en:'Californium',  ja:'カリホルニウム', fact:'中性子源として利用。'},
  {num:99,  sym:'Es', en:'Einsteinium',  ja:'アインスタイニウム',fact:'超重元素研究用。'},
  {num:100,sym:'Fm', en:'Fermium',       ja:'フェルミウム',   fact:'水爆実験で生成が確認。'},
  {num:101,sym:'Md', en:'Mendelevium',   ja:'メンデレビウム', fact:'初の個数単位合成元素。'},
  {num:102,sym:'No', en:'Nobelium',      ja:'ノーベリウム',   fact:'α崩壊列研究。'},
  {num:103,sym:'Lr', en:'Lawrencium',    ja:'ローレンシウム', fact:'アクチノイド最終元素。'},

  {num:104,sym:'Rf', en:'Rutherfordium', ja:'ラザフォージウム',fact:'最初に命名が議論となった超重元素。'},
  {num:105,sym:'Db', en:'Dubnium',       ja:'ドブニウム',     fact:'ドゥブナ（ロシア）で発見。'},
  {num:106,sym:'Sg', en:'Seaborgium',    ja:'シーボーギウム', fact:'グレン・シーボーグに因む。'},
  {num:107,sym:'Bh', en:'Bohrium',       ja:'ボーリウム',     fact:'ニールス・ボーアを称える。'},
  {num:108,sym:'Hs', en:'Hassium',       ja:'ハッシウム',     fact:'発見地ダルムシュタット州の古名。'},
  {num:109,sym:'Mt', en:'Meitnerium',    ja:'マイトネリウム', fact:'物理学者リーゼ・マイトナーに献名。'},
  {num:110,sym:'Ds', en:'Darmstadtium',  ja:'ダームスタチウム',fact:'ドイツのダルムシュタットで合成。'},
  {num:111,sym:'Rg', en:'Roentgenium',   ja:'レントゲニウム', fact:'X線発見者レントゲンに献名。'},
  {num:112,sym:'Cn', en:'Copernicium',   ja:'コペルニシウム', fact:'地動説のコペルニクスに因む。'},
  {num:113,sym:'Nh', en:'Nihonium',      ja:'ニホニウム',     fact:'理研で合成、日本にちなむ名称。'},
  {num:114,sym:'Fl', en:'Flerovium',     ja:'フレロビウム',   fact:'フレロフ核物理研究所に由来。'},
  {num:115,sym:'Mc', en:'Moscovium',     ja:'モスコビウム',   fact:'モスクワ州に因む。'},
  {num:116,sym:'Lv', en:'Livermorium',   ja:'リバモリウム',   fact:'米国リバモア研究所に献名。'},
  {num:117,sym:'Ts', en:'Tennessine',    ja:'テネシン',       fact:'米国テネシー州に敬意。'},
  {num:118,sym:'Og', en:'Oganesson',     ja:'オガネソン',     fact:'ユーリ・オガネシアンに献名。'}
];